name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install system dependencies for PyAudio (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python-pyaudio python3-pyaudio
      
    - name: Install system dependencies for PyAudio (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install portaudio
      
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov build twine
    
    - name: Install package with mock PyAudio
      run: |
        # Create a mock PyAudio module to satisfy dependencies
        mkdir -p mock_modules
        echo "# Mock PyAudio module for CI testing" > mock_modules/pyaudio.py
        echo "class PyAudio: pass" >> mock_modules/pyaudio.py
        echo "def paInt16(): return 16" >> mock_modules/pyaudio.py
        # Add the mock modules directory to Python path
        echo "PYTHONPATH=./mock_modules:$PYTHONPATH" >> $GITHUB_ENV
        # Install the package in development mode
        pip install -e .
    
    - name: Test with pytest (without audio functionality)
      run: |
        pytest --cov=dhvagna_npi tests/ -k "not test_audio"
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check distributions
      run: |
        twine check dist/*
    
    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/
        retention-days: 7
